version: "3"
services:
  api:
    image: qa/microservice
    build:
      context: .
      dockerfile: Dockerfile
      args:
      - PASS=rootpass
    ports:
      - "8080:8080"
      - "2222:22"
    volumes:
      - "./src:/opt/microservice"